services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: planner
      POSTGRES_PASSWORD: plannerpw
      POSTGRES_DB: plannerdb
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  backend:
    build: ./anka-case-backend
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://planner:plannerpw@db:5432/plannerdb
    ports:
      - "3333:3333"
  frontend:
    build: ./anka-case-frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"

volumes:
  pg_data:
